;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Effect.Drunk",DevComment="Debuff: drunk")
+GameplayTagList=(Tag="Effect.WellFed",DevComment="Buff: well fed")
+GameplayTagList=(Tag="Stat.Damage.Received",DevComment="Globald damage multiplier")
+GameplayTagList=(Tag="Stat.Health.Regen",DevComment="Health regen")
+GameplayTagList=(Tag="Stat.Hunger.Decay",DevComment="Hunger decay")
+GameplayTagList=(Tag="Stat.Hunger.Regen",DevComment="Hunger regeneration")
+GameplayTagList=(Tag="Stat.Stamina.Decay",DevComment="Stamina decay")
+GameplayTagList=(Tag="Stat.Stamina.Regen",DevComment="Stamina Regeneration")
+GameplayTagList=(Tag="Stat.Thirst.Decay",DevComment="Thirst decay")
+GameplayTagList=(Tag="Stat.Thirst.Regen",DevComment="Thirst regeneration")

